project_home_path:
  C:/Users/dongz/PycharmProjects/2021-msia423-dong-zizhuo-project/
data_source_url:
  https://www1.nyc.gov/assets/nypd/downloads/excel/analysis_and_planning/stop-question-frisk/sqf-2015.csv
s3:
  DEST_S3_BUCKET: msia423-dong
  PATH: raw/
local_data_path:
  PATH: C:/Users/dongz/PycharmProjects/2021-msia423-dong-zizhuo-project/data/raw/sqf-2015.csv
sample_data:
  PATH: ./data/sample/

rds:
  HOST_NAME: msia423-dong.cai6yic8dlms.us-east-2.rds.amazonaws.com
  PORT_NO: 3306
  DATABASE_NAME: msia423_db
  CONN_TYPE: mysql+pymysql
sqlitedb:
  DB_PATH: data/sqf_sqlite.db
